### ISSUE TITLE
Does This Work With .NET Core

### ISSUE THREAD

**Issue by RealDotNetDave** [brutaldev/StrongNameSigner#46] opened 2018-06-25 15:51 UTC
I'm trying to use this with .NET Core and am getting the following errors:

2>C:\Users\dotnetdave\.nuget\packages\brutal.dev.strongnamesigner\2.1.4\build\Brutal.Dev.StrongNameSigner.targets(6,5): error : Operation is not valid due to the current state of the object.
2>C:\Users\dotnetdave\.nuget\packages\brutal.dev.strongnamesigner\2.1.4\build\Brutal.Dev.StrongNameSigner.targets(6,5): error :    at Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
2>C:\Users\dotnetdave\.nuget\packages\brutal.dev.strongnamesigner\2.1.4\build\Brutal.Dev.StrongNameSigner.targets(6,5): error :    at Mono.Cecil.ModuleDefinition.ReadSymbols(ISymbolReader reader)
2>C:\Users\dotnetdave\.nuget\packages\brutal.dev.strongnamesigner\2.1.4\build\Brutal.Dev.StrongNameSigner.targets(6,5): error :    at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
2>C:\Users\dotnetdave\.nuget\packages\brutal.dev.strongnamesigner\2.1.4\build\Brutal.Dev.StrongNameSigner.targets(6,5): error :    at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
2>C:\Users\dotnetdave\.nuget\packages\brutal.dev.strongnamesigner\2.1.4\build\Brutal.Dev.StrongNameSigner.targets(6,5): error :    at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
2>C:\Users\dotnetdave\.nuget\packages\brutal.dev.strongnamesigner\2.1.4\build\Brutal.Dev.StrongNameSigner.targets(6,5): error :    at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
2>C:\Users\dotnetdave\.nuget\packages\brutal.dev.strongnamesigner\2.1.4\build\Brutal.Dev.StrongNameSigner.targets(6,5): error :    at Brutal.Dev.StrongNameSigner.SigningHelper.GetAssemblyInfo(String assemblyPath, String[] probingPaths)
2>C:\Users\dotnetdave\.nuget\packages\brutal.dev.strongnamesigner\2.1.4\build\Brutal.Dev.StrongNameSigner.targets(6,5): error :    at Brutal.Dev.StrongNameSigner.AutomaticBuildTask.Execute()

**Comment by brutaldev** [comment] 2018-06-25 15:52
Duplicate of https://github.com/brutaldev/StrongNameSigner/issues/41

**Closed by brutaldev** 2018-06-25 15:52 UTC
Labels: duplicate
